name: Deploy and Run
env:
  REPO_NAME: ${{ github.event.repository.name }}
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
     
    - name: 'Login via Docker'
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_NAME_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.ACR_NAME_URL }}/${{env.REPO_NAME}}:${{ github.sha }}
        docker push ${{ secrets.ACR_NAME_URL }}/${{env.REPO_NAME}}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'deploy Container Instance'
      uses: azure/aci-deploy@v1
      with:
        location: eastus
        name: azureapp
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        image: ${{ secrets.ACR_NAME_URL }}/${{env.REPO_NAME}}:${{ github.sha }}
        dns-name-label: azureapp-${{ github.run_id }}-${{ github.run_attempt }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        ports: 8080
        cpu: 0.25
        memory: 0.5
    
    - name: 'logout'
      run: |
        az logout
      #TODO:Que si viene con una etiqueta o con un tag, me cree una imagen con la etiqueta o con el tag en donde es del tipo vX.Y.Z que se envio y ademas, ver de actualizar las versiones de los scripts.