name: Deploy and Run
env:
  REPO_NAME: ${{ github.event.repository.name }}
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
     
    - name: 'Login via Docker'
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_NAME_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: 'Build and push Docker image'
      run: |
        if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
          docker build . -t ${{ secrets.ACR_NAME_URL }}/${{env.REPO_NAME}}:${VERSION}
          docker push ${{ secrets.ACR_NAME_URL }}/${{env.REPO_NAME}}:${VERSION}
        else
          docker build . -t ${{ secrets.ACR_NAME_URL }}/${{env.REPO_NAME}}:${{ github.sha }}
          docker push ${{ secrets.ACR_NAME_URL }}/${{env.REPO_NAME}}:${{ github.sha }}
        fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'deploy Container Instance'
      uses: azure/aci-deploy@v1
      with:
        location: brazilsouth
        name: azureapp
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        image: ${{ secrets.ACR_NAME_URL }}/${{env.REPO_NAME}}:${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || github.sha }}
        dns-name-label: azureapp-${{ github.run_id }}-${{ github.run_attempt }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        ports: 8080
        cpu: 0.25
        memory: 0.5
    
    - name: 'logout'
      run: |
        az logout